"""Emoji picker dialog for Markdown Editor.

Provides a searchable emoji picker with categories and grid display.
"""

from __future__ import annotations

from PyQt6.QtCore import QSize, Qt, pyqtSignal
from PyQt6.QtGui import QFont
from PyQt6.QtWidgets import (
    QComboBox,
    QDialog,
    QLabel,
    QLineEdit,
    QListWidget,
    QListWidgetItem,
    QPushButton,
    QVBoxLayout,
    QWidget,
)

from markdown_editor_pkg.i18n import tr

# ─── Данные emoji (ключи — английские, всегда одинаковые) ───────────────────

EMOJI_DATA: dict[str, list[tuple[str, str]]] = {
    "smileys": [
        ("😀", "Grinning Face"),
        ("😃", "Grinning Face with Big Eyes"),
        ("😄", "Grinning Face with Smiling Eyes"),
        ("😁", "Beaming Face with Smiling Eyes"),
        ("😆", "Grinning Squinting Face"),
        ("😅", "Grinning Face with Sweat"),
        ("🤣", "Rolling on the Floor Laughing"),
        ("😂", "Face with Tears of Joy"),
        ("🙂", "Slightly Smiling Face"),
        ("🙃", "Upside-Down Face"),
        ("😉", "Winking Face"),
        ("😊", "Smiling Face with Smiling Eyes"),
        ("😇", "Smiling Face with Halo"),
        ("🥰", "Smiling Face with Hearts"),
        ("😍", "Smiling Face with Heart-Eyes"),
        ("🤩", "Star-Struck"),
        ("😘", "Face Blowing a Kiss"),
        ("😗", "Kissing Face"),
        ("☺️", "Smiling Face"),
        ("😚", "Kissing Face with Closed Eyes"),
        ("😙", "Kissing Face with Smiling Eyes"),
        ("😋", "Face Savoring Food"),
        ("😛", "Face with Tongue"),
        ("😜", "Winking Face with Tongue"),
        ("🤪", "Zany Face"),
        ("😝", "Squinting Face with Tongue"),
        ("🤑", "Money-Mouth Face"),
        ("🤗", "Hugging Face"),
        ("🤭", "Face with Hand Over Mouth"),
        ("🤫", "Shushing Face"),
        ("🤔", "Thinking Face"),
        ("😐", "Neutral Face"),
        ("😑", "Expressionless Face"),
        ("😶", "Face Without Mouth"),
        ("😏", "Smirking Face"),
        ("😒", "Unamused Face"),
        ("🙄", "Face with Rolling Eyes"),
        ("😬", "Grimacing Face"),
        ("😌", "Relieved Face"),
        ("😔", "Pensive Face"),
        ("😪", "Sleepy Face"),
        ("🤤", "Drooling Face"),
        ("😴", "Sleeping Face"),
        ("😷", "Face with Medical Mask"),
        ("🤒", "Face with Thermometer"),
        ("🤕", "Face with Head-Bandage"),
        ("🤢", "Nauseated Face"),
        ("🤮", "Face Vomiting"),
        ("🥵", "Hot Face"),
        ("🥶", "Cold Face"),
        ("🥴", "Woozy Face"),
        ("😵", "Dizzy Face"),
        ("🤯", "Exploding Head"),
        ("🤠", "Cowboy Hat Face"),
        ("🥳", "Partying Face"),
        ("😎", "Smiling Face with Sunglasses"),
        ("🤓", "Nerd Face"),
        ("🧐", "Face with Monocle"),
        ("😕", "Confused Face"),
        ("😟", "Worried Face"),
        ("🙁", "Frowning Face"),
        ("😮", "Face with Open Mouth"),
        ("😯", "Hushed Face"),
        ("😲", "Astonished Face"),
        ("😳", "Flushed Face"),
        ("🥺", "Pleading Face"),
        ("😦", "Frowning Face with Open Mouth"),
        ("😧", "Anguished Face"),
        ("😨", "Fearful Face"),
        ("😰", "Anxious Face with Sweat"),
        ("😥", "Sad but Relieved Face"),
        ("😢", "Crying Face"),
        ("😭", "Loudly Crying Face"),
        ("😱", "Face Screaming in Fear"),
        ("😖", "Confounded Face"),
        ("😣", "Persevering Face"),
        ("😞", "Disappointed Face"),
        ("😓", "Downcast Face with Sweat"),
        ("😩", "Weary Face"),
        ("😫", "Tired Face"),
        ("🥱", "Yawning Face"),
        ("😤", "Face with Steam From Nose"),
        ("😡", "Pouting Face"),
        ("😠", "Angry Face"),
        ("🤬", "Face with Symbols on Mouth"),
        ("😈", "Smiling Face with Horns"),
        ("👿", "Angry Face with Horns"),
        ("💀", "Skull"),
        ("☠️", "Skull and Crossbones"),
        ("💩", "Pile of Poo"),
        ("🤡", "Clown Face"),
        ("👹", "Ogre"),
        ("👺", "Goblin"),
        ("👻", "Ghost"),
        ("👽", "Alien"),
        ("👾", "Alien Monster"),
        ("🤖", "Robot"),
        ("😺", "Grinning Cat"),
        ("😸", "Grinning Cat with Smiling Eyes"),
        ("😹", "Cat with Tears of Joy"),
        ("😻", "Smiling Cat with Heart-Eyes"),
        ("😼", "Cat with Wry Smile"),
        ("😽", "Kissing Cat"),
        ("🙀", "Weary Cat"),
        ("😿", "Crying Cat"),
        ("😾", "Pouting Cat"),
    ],
    "gestures": [
        ("👋", "Waving Hand"),
        ("🤚", "Raised Back of Hand"),
        ("🖐️", "Hand with Fingers Splayed"),
        ("✋", "Raised Hand"),
        ("🖖", "Vulcan Salute"),
        ("👌", "OK Hand"),
        ("🤌", "Pinched Fingers"),
        ("🤏", "Pinching Hand"),
        ("✌️", "Victory Hand"),
        ("🤞", "Crossed Fingers"),
        ("🤟", "Love-You Gesture"),
        ("🤘", "Sign of the Horns"),
        ("🤙", "Call Me Hand"),
        ("👈", "Backhand Index Pointing Left"),
        ("👉", "Backhand Index Pointing Right"),
        ("👆", "Backhand Index Pointing Up"),
        ("🖕", "Middle Finger"),
        ("👇", "Backhand Index Pointing Down"),
        ("☝️", "Index Pointing Up"),
        ("👍", "Thumbs Up"),
        ("👎", "Thumbs Down"),
        ("✊", "Raised Fist"),
        ("👊", "Oncoming Fist"),
        ("🤛", "Left-Facing Fist"),
        ("🤜", "Right-Facing Fist"),
        ("👏", "Clapping Hands"),
        ("🙌", "Raising Hands"),
        ("🫶", "Heart Hands"),
        ("👐", "Open Hands"),
        ("🤲", "Palms Up Together"),
        ("🤝", "Handshake"),
        ("🙏", "Folded Hands"),
        ("✍️", "Writing Hand"),
        ("💅", "Nail Polish"),
        ("🤳", "Selfie"),
        ("💪", "Flexed Biceps"),
        ("🦾", "Mechanical Arm"),
        ("🦿", "Mechanical Leg"),
        ("🦵", "Leg"),
        ("🦶", "Foot"),
        ("👂", "Ear"),
        ("🦻", "Ear with Hearing Aid"),
        ("👃", "Nose"),
    ],
    "hearts": [
        ("❤️", "Red Heart"),
        ("🧡", "Orange Heart"),
        ("💛", "Yellow Heart"),
        ("💚", "Green Heart"),
        ("💙", "Blue Heart"),
        ("💜", "Purple Heart"),
        ("🖤", "Black Heart"),
        ("🤍", "White Heart"),
        ("🤎", "Brown Heart"),
        ("💔", "Broken Heart"),
        ("❤️‍🔥", "Heart on Fire"),
        ("❤️‍🩹", "Mending Heart"),
        ("❣️", "Heavy Heart Exclamation"),
        ("💕", "Two Hearts"),
        ("💞", "Revolving Hearts"),
        ("💓", "Beating Heart"),
        ("💗", "Growing Heart"),
        ("💖", "Sparkling Heart"),
        ("💘", "Heart with Arrow"),
        ("💝", "Heart with Ribbon"),
        ("💟", "Heart Decoration"),
        ("♥️", "Heart Suit"),
    ],
    "nature": [
        ("🐵", "Monkey Face"),
        ("🐒", "Monkey"),
        ("🦍", "Gorilla"),
        ("🐶", "Dog Face"),
        ("🐕", "Dog"),
        ("🐩", "Poodle"),
        ("🐺", "Wolf"),
        ("🦊", "Fox"),
        ("🦝", "Raccoon"),
        ("🐱", "Cat Face"),
        ("🐈", "Cat"),
        ("🦁", "Lion"),
        ("🐯", "Tiger Face"),
        ("🐅", "Tiger"),
        ("🐆", "Leopard"),
        ("🐴", "Horse Face"),
        ("🐎", "Horse"),
        ("🦄", "Unicorn"),
        ("🦓", "Zebra"),
        ("🦌", "Deer"),
        ("🐮", "Cow Face"),
        ("🐂", "Ox"),
        ("🐄", "Cow"),
        ("🐷", "Pig Face"),
        ("🐖", "Pig"),
        ("🐗", "Boar"),
        ("🐽", "Pig Nose"),
        ("🐏", "Ram"),
        ("🐑", "Ewe"),
        ("🐐", "Goat"),
        ("🐪", "Camel"),
        ("🐫", "Two-Hump Camel"),
        ("🐘", "Elephant"),
        ("🦏", "Rhinoceros"),
        ("🦛", "Hippopotamus"),
        ("🐭", "Mouse Face"),
        ("🐁", "Mouse"),
        ("🐀", "Rat"),
        ("🐹", "Hamster"),
        ("🐰", "Rabbit Face"),
        ("🐇", "Rabbit"),
        ("🐿️", "Chipmunk"),
        ("🐻", "Bear"),
        ("🐻‍❄️", "Polar Bear"),
        ("🐨", "Koala"),
        ("🐼", "Panda"),
        ("🦥", "Sloth"),
        ("🦦", "Otter"),
        ("🦨", "Skunk"),
        ("🦘", "Kangaroo"),
        ("🦡", "Badger"),
        ("🐾", "Paw Prints"),
        ("🦃", "Turkey"),
        ("🐔", "Chicken"),
        ("🐓", "Rooster"),
        ("🐣", "Hatching Chick"),
        ("🐤", "Baby Chick"),
        ("🐥", "Front-Facing Baby Chick"),
        ("🐦", "Bird"),
        ("🐧", "Penguin"),
        ("🕊️", "Dove"),
        ("🦅", "Eagle"),
        ("🦆", "Duck"),
        ("🦢", "Swan"),
        ("🦉", "Owl"),
        ("🦚", "Peacock"),
        ("🦜", "Parrot"),
        ("🐸", "Frog"),
        ("🐊", "Crocodile"),
        ("🐢", "Turtle"),
        ("🦎", "Lizard"),
        ("🐍", "Snake"),
        ("🐲", "Dragon Face"),
        ("🐉", "Dragon"),
        ("🦕", "Sauropod"),
        ("🦖", "T-Rex"),
        ("🐳", "Spouting Whale"),
        ("🐋", "Whale"),
        ("🐬", "Dolphin"),
        ("🦭", "Seal"),
        ("🐟", "Fish"),
        ("🐠", "Tropical Fish"),
        ("🐡", "Blowfish"),
        ("🦈", "Shark"),
        ("🐙", "Octopus"),
        ("🐚", "Spiral Shell"),
        ("🐌", "Snail"),
        ("🦋", "Butterfly"),
        ("🐛", "Bug"),
        ("🐜", "Ant"),
        ("🐝", "Honeybee"),
        ("🐞", "Lady Beetle"),
        ("🦗", "Cricket"),
        ("🦂", "Scorpion"),
        ("🦟", "Mosquito"),
        ("💐", "Bouquet"),
        ("🌸", "Cherry Blossom"),
        ("💮", "White Flower"),
        ("🏵️", "Rosette"),
        ("🌹", "Rose"),
        ("🥀", "Wilted Flower"),
        ("🌺", "Hibiscus"),
        ("🌻", "Sunflower"),
        ("🌼", "Blossom"),
        ("🌷", "Tulip"),
        ("🌱", "Seedling"),
        ("🌲", "Evergreen Tree"),
        ("🌳", "Deciduous Tree"),
        ("🌴", "Palm Tree"),
        ("🌵", "Cactus"),
        ("🌾", "Sheaf of Rice"),
        ("🌿", "Herb"),
        ("☘️", "Shamrock"),
        ("🍀", "Four Leaf Clover"),
        ("🍁", "Maple Leaf"),
        ("🍂", "Fallen Leaf"),
        ("🍃", "Leaf Fluttering in Wind"),
        ("🍄", "Mushroom"),
        ("🌰", "Chestnut"),
        ("🥬", "Leafy Green"),
        ("🧄", "Garlic"),
        ("🧅", "Onion"),
        ("🥜", "Peanuts"),
        ("🌰", "Chestnut"),
    ],
    "food": [
        ("🍇", "Grapes"),
        ("🍈", "Melon"),
        ("🍉", "Watermelon"),
        ("🍊", "Tangerine"),
        ("🍋", "Lemon"),
        ("🍌", "Banana"),
        ("🍍", "Pineapple"),
        ("🥭", "Mango"),
        ("🍎", "Red Apple"),
        ("🍏", "Green Apple"),
        ("🍐", "Pear"),
        ("🍑", "Peach"),
        ("🍒", "Cherries"),
        ("🍓", "Strawberry"),
        ("🥝", "Kiwi Fruit"),
        ("🍅", "Tomato"),
        ("🥑", "Avocado"),
        ("🍆", "Eggplant"),
        ("🥔", "Potato"),
        ("🥕", "Carrot"),
        ("🌽", "Ear of Corn"),
        ("🌶️", "Hot Pepper"),
        ("🥒", "Cucumber"),
        ("🥦", "Broccoli"),
        ("🧄", "Garlic"),
        ("🧅", "Onion"),
        ("🥜", "Peanuts"),
        ("🌰", "Chestnut"),
        ("🍞", "Bread"),
        ("🥐", "Croissant"),
        ("🥖", "Baguette Bread"),
        ("🥨", "Pretzel"),
        ("🥯", "Bagel"),
        ("🥞", "Pancakes"),
        ("🧀", "Cheese Wedge"),
        ("🍖", "Meat on Bone"),
        ("🍗", "Poultry Leg"),
        ("🥩", "Cut of Meat"),
        ("🥓", "Bacon"),
        ("🍔", "Hamburger"),
        ("🍟", "French Fries"),
        ("🍕", "Pizza"),
        ("🌭", "Hot Dog"),
        ("🥪", "Sandwich"),
        ("🌮", "Taco"),
        ("🌯", "Burrito"),
        ("🥙", "Stuffed Flatbread"),
        ("🥚", "Egg"),
        ("🍳", "Cooking"),
        ("🥘", "Shallow Pan of Food"),
        ("🍲", "Pot of Food"),
        ("🥣", "Bowl with Spoon"),
        ("🥗", "Green Salad"),
        ("🍿", "Popcorn"),
        ("🧂", "Salt"),
        ("🥫", "Canned Food"),
        ("🍱", "Bento Box"),
        ("🍘", "Rice Cracker"),
        ("🍙", "Rice Ball"),
        ("🍚", "Cooked Rice"),
        ("🍛", "Curry Rice"),
        ("🍜", "Steaming Bowl"),
        ("🍝", "Spaghetti"),
        ("🍠", "Roasted Sweet Potato"),
        ("🍢", "Oden"),
        ("🍣", "Sushi"),
        ("🍤", "Fried Shrimp"),
        ("🍥", "Fish Cake with Swirl"),
        ("🍡", "Dango"),
        ("🥟", "Dumpling"),
        ("🥠", "Fortune Cookie"),
        ("🥡", "Takeout Box"),
        ("🦀", "Crab"),
        ("🦞", "Lobster"),
        ("🦐", "Shrimp"),
        ("🦑", "Squid"),
        ("🦪", "Oyster"),
        ("🍦", "Soft Ice Cream"),
        ("🍧", "Shaved Ice"),
        ("🍨", "Ice Cream"),
        ("🍩", "Doughnut"),
        ("🍪", "Cookie"),
        ("🎂", "Birthday Cake"),
        ("🍰", "Shortcake"),
        ("🧁", "Cupcake"),
        ("🥧", "Pie"),
        ("🍫", "Chocolate Bar"),
        ("🍬", "Candy"),
        ("🍭", "Lollipop"),
        ("🍮", "Custard"),
        ("🍯", "Honey Pot"),
        ("🍼", "Baby Bottle"),
        ("🥛", "Glass of Milk"),
        ("☕", "Hot Beverage"),
        ("🍵", "Teacup Without Handle"),
        ("🍶", "Sake"),
        ("🍺", "Beer Mug"),
        ("🍻", "Clinking Beer Mugs"),
        ("🥂", "Clinking Glasses"),
        ("🍷", "Wine Glass"),
        ("🥃", "Tumbler Glasses"),
        ("🥤", "Cup with Straw"),
        ("🧃", "Beverage Box"),
        ("🥢", "Chopsticks"),
        ("🍽️", "Fork and Knife with Plate"),
        ("🍴", "Fork and Knife"),
        ("🥄", "Spoon"),
    ],
    "travel": [
        ("🚗", "Automobile"),
        ("🚕", "Taxi"),
        ("🚙", "Sport Utility Vehicle"),
        ("🚌", "Bus"),
        ("🚎", "Trolleybus"),
        ("🏎️", "Racing Car"),
        ("🚓", "Police Car"),
        ("🚑", "Ambulance"),
        ("🚒", "Fire Engine"),
        ("🚐", "Minibus"),
        ("🚚", "Delivery Truck"),
        ("🚛", "Articulated Lorry"),
        ("🚜", "Tractor"),
        ("🏍️", "Motorcycle"),
        ("🛵", "Motor Scooter"),
        ("🚲", "Bicycle"),
        ("🛴", "Kick Scooter"),
        ("🛹", "Skateboard"),
        ("🚏", "Bus Stop"),
        ("🛣️", "Motorway"),
        ("⛽", "Fuel Pump"),
        ("🚨", "Police Car Light"),
        ("🚥", "Horizontal Traffic Light"),
        ("🚦", "Vertical Traffic Light"),
        ("🛑", "Stop Sign"),
        ("🚧", "Construction"),
        ("⚓", "Anchor"),
        ("⛵", "Sailboat"),
        ("🛶", "Canoe"),
        ("🚤", "Speedboat"),
        ("🛳️", "Passenger Ship"),
        ("⛴️", "Ferry"),
        ("🚢", "Ship"),
        ("✈️", "Airplane"),
        ("🛩️", "Small Airplane"),
        ("🛫", "Airplane Departure"),
        ("🛬", "Airplane Arrival"),
        ("💺", "Seat"),
        ("🚁", "Helicopter"),
        ("🚀", "Rocket"),
        ("🛸", "Flying Saucer"),
        ("🛎️", "Bellhop Bell"),
        ("🧳", "Luggage"),
        ("⌛", "Hourglass Done"),
        ("⏳", "Hourglass Not Done"),
        ("⌚", "Watch"),
        ("⏰", "Alarm Clock"),
        ("⏱️", "Stopwatch"),
        ("⏲️", "Timer Clock"),
        ("🕰️", "Mantelpiece Clock"),
        ("🕛", "Twelve O'Clock"),
        ("🕐", "One O'Clock"),
        ("🕑", "Two O'Clock"),
        ("🕒", "Three O'Clock"),
        ("🕓", "Four O'Clock"),
        ("🕔", "Five O'Clock"),
        ("🕕", "Six O'Clock"),
        ("🕖", "Seven O'Clock"),
        ("🕗", "Eight O'Clock"),
        ("🕘", "Nine O'Clock"),
        ("🕙", "Ten O'Clock"),
        ("🕚", "Eleven O'Clock"),
        ("🌑", "New Moon"),
        ("🌒", "Waxing Crescent Moon"),
        ("🌓", "First Quarter Moon"),
        ("🌔", "Waxing Gibbous Moon"),
        ("🌕", "Full Moon"),
        ("🌖", "Waning Gibbous Moon"),
        ("🌗", "Last Quarter Moon"),
        ("🌘", "Waning Crescent Moon"),
        ("🌙", "Crescent Moon"),
        ("🌚", "New Moon Face"),
        ("🌛", "First Quarter Moon Face"),
        ("🌜", "Last Quarter Moon Face"),
        ("☀️", "Sun"),
        ("🌝", "Full Moon Face"),
        ("🌞", "Sun with Face"),
        ("⭐", "Star"),
        ("🌟", "Glowing Star"),
        ("🌠", "Shooting Star"),
        ("🌌", "Milky Way"),
        ("☁️", "Cloud"),
        ("⛅", "Sun Behind Cloud"),
        ("⛈️", "Cloud with Lightning and Rain"),
        ("🌤️", "Sun Behind Small Cloud"),
        ("🌥️", "Sun Behind Large Cloud"),
        ("🌦️", "Sun Behind Rain Cloud"),
        ("🌧️", "Cloud with Rain"),
        ("🌨️", "Cloud with Snow"),
        ("🌩️", "Cloud with Lightning"),
        ("🌪️", "Tornado"),
        ("🌫️", "Fog"),
        ("🌬️", "Wind Face"),
        ("🌀", "Cyclone"),
        ("🌈", "Rainbow"),
        ("🌂", "Closed Umbrella"),
        ("☂️", "Umbrella"),
        ("☔", "Umbrella with Rain Drops"),
        ("⛱️", "Umbrella on Ground"),
        ("⚡", "High Voltage"),
        ("❄️", "Snowflake"),
        ("☃️", "Snowman"),
        ("⛄", "Snowman Without Snow"),
        ("☄️", "Comet"),
        ("🔥", "Fire"),
        ("💧", "Drop of Water"),
        ("🌊", "Water Wave"),
    ],
    "objects": [
        ("🎃", "Jack-O-Lantern"),
        ("🎄", "Christmas Tree"),
        ("🎆", "Fireworks"),
        ("🎇", "Sparkler"),
        ("🧨", "Firecracker"),
        ("✨", "Sparkles"),
        ("🎈", "Balloon"),
        ("🎉", "Party Popper"),
        ("🎊", "Confetti Ball"),
        ("🎋", "Tanabata Tree"),
        ("🎍", "Pine Decoration"),
        ("🎎", "Japanese Dolls"),
        ("🎏", "Carp Streamer"),
        ("🎐", "Wind Chime"),
        ("🎑", "Moon Viewing Ceremony"),
        ("🧧", "Red Envelope"),
        ("🎀", "Ribbon"),
        ("🎁", "Wrapped Gift"),
        ("🎗️", "Reminder Ribbon"),
        ("🎟️", "Admission Tickets"),
        ("🎫", "Ticket"),
        ("🎖️", "Military Medal"),
        ("🏆", "Trophy"),
        ("🏅", "Sports Medal"),
        ("🥇", "1st Place Medal"),
        ("🥈", "2nd Place Medal"),
        ("🥉", "3rd Place Medal"),
        ("⚽", "Soccer Ball"),
        ("⚾", "Baseball"),
        ("🥎", "Softball"),
        ("🏀", "Basketball"),
        ("🏐", "Volleyball"),
        ("🏈", "American Football"),
        ("🏉", "Rugby Football"),
        ("🎾", "Tennis"),
        ("🎳", "Bowling"),
        ("🏏", "Cricket Game"),
        ("🏑", "Field Hockey"),
        ("🏒", "Ice Hockey"),
        ("🥍", "Lacrosse"),
        ("🏓", "Ping Pong"),
        ("🏸", "Badminton"),
        ("🥊", "Boxing Glove"),
        ("🥋", "Martial Arts Uniform"),
        ("🥅", "Goal Net"),
        ("⛳", "Flag in Hole"),
        ("⛸️", "Ice Skate"),
        ("🎣", "Fishing Pole"),
        ("🎽", "Running Shirt"),
        ("🎿", "Skis"),
        ("🎯", "Direct Hit"),
        ("🎱", "Pool 8 Ball"),
        ("🔮", "Crystal Ball"),
        ("🧩", "Puzzle Piece"),
        ("🧸", "Teddy Bear"),
        ("♠️", "Spade Suit"),
        ("♥️", "Heart Suit"),
        ("♦️", "Diamond Suit"),
        ("♣️", "Club Suit"),
        ("🃏", "Joker"),
        ("🀄", "Mahjong Red Dragon"),
        ("🎴", "Flower Playing Cards"),
        ("🎭", "Performing Arts"),
        ("🖼️", "Framed Picture"),
        ("🎨", "Artist Palette"),
        ("🧵", "Thread"),
        ("🪡", "Sewing Needle"),
        ("🧶", "Yarn"),
        ("👓", "Glasses"),
        ("🕶️", "Sunglasses"),
        ("🥽", "Goggles"),
        ("👔", "Necktie"),
        ("👕", "T-Shirt"),
        ("👖", "Jeans"),
        ("🧣", "Scarf"),
        ("🧤", "Gloves"),
        ("🧥", "Coat"),
        ("🧦", "Socks"),
        ("👗", "Dress"),
        ("👘", "Kimono"),
        ("👙", "Bikini"),
        ("👚", "Woman's Clothes"),
        ("👛", "Purse"),
        ("👜", "Handbag"),
        ("👝", "Clutch Bag"),
        ("🛍️", "Shopping Bags"),
        ("🎒", "Backpack"),
        ("👞", "Man's Shoe"),
        ("👟", "Running Shoe"),
        ("🥾", "Hiking Boot"),
        ("🥿", "Flat Shoe"),
        ("👠", "High-Heeled Shoe"),
        ("👡", "Woman's Sandal"),
        ("👢", "Woman's Boot"),
        ("👑", "Crown"),
        ("👒", "Woman's Hat"),
        ("🎩", "Top Hat"),
        ("🎓", "Graduation Cap"),
        ("🧢", "Billed Cap"),
        ("⛑️", "Rescue Worker's Helmet"),
        ("📿", "Prayer Beads"),
        ("💄", "Lipstick"),
        ("💍", "Ring"),
        ("💎", "Gem Stone"),
        ("🔇", "Muted Speaker"),
        ("🔈", "Speaker Low Volume"),
        ("🔉", "Speaker Medium Volume"),
        ("🔊", "Speaker High Volume"),
        ("📢", "Loudspeaker"),
        ("📣", "Megaphone"),
        ("🔔", "Bell"),
        ("🔕", "Bell with Slash"),
        ("🎼", "Musical Score"),
        ("🎵", "Musical Note"),
        ("🎶", "Musical Notes"),
        ("🎙️", "Studio Microphone"),
        ("🎚️", "Level Slider"),
        ("🎛️", "Control Knobs"),
        ("🎤", "Microphone"),
        ("🎧", "Headphone"),
        ("📻", "Radio"),
        ("🎷", "Saxophone"),
        ("🎸", "Guitar"),
        ("🎹", "Musical Keyboard"),
        ("🎺", "Trumpet"),
        ("🎻", "Violin"),
        ("🥁", "Drum"),
        ("📱", "Mobile Phone"),
        ("📲", "Mobile Phone with Arrow"),
        ("☎️", "Telephone"),
        ("📞", "Telephone Receiver"),
        ("📟", "Pager"),
        ("📠", "Fax Machine"),
        ("🔋", "Battery"),
        ("🔌", "Electric Plug"),
        ("💻", "Laptop"),
        ("🖥️", "Desktop Computer"),
        ("🖨️", "Printer"),
        ("⌨️", "Keyboard"),
        ("🖱️", "Computer Mouse"),
        ("💽", "Computer Disk"),
        ("💾", "Floppy Disk"),
        ("💿", "Optical Disk"),
        ("📀", "DVD"),
        ("🎥", "Movie Camera"),
        ("🎞️", "Film Frames"),
        ("📽️", "Film Projector"),
        ("📺", "Television"),
        ("📷", "Camera"),
        ("📸", "Camera with Flash"),
        ("📹", "Video Camera"),
        ("📼", "Videocassette"),
        ("🔍", "Magnifying Glass Tilted Left"),
        ("🔎", "Magnifying Glass Tilted Right"),
        ("🕯️", "Candle"),
        ("💡", "Light Bulb"),
        ("🔦", "Flashlight"),
        ("🏮", "Red Paper Lantern"),
        ("📔", "Notebook with Decorative Cover"),
        ("📕", "Closed Book"),
        ("📖", "Open Book"),
        ("📗", "Green Book"),
        ("📘", "Blue Book"),
        ("📙", "Orange Book"),
        ("📚", "Books"),
        ("📓", "Notebook"),
        ("📒", "Ledger"),
        ("📃", "Page with Curl"),
        ("📜", "Scroll"),
        ("📄", "Page Facing Up"),
        ("📰", "Newspaper"),
        ("🗞️", "Rolled-Up Newspaper"),
        ("📑", "Bookmark Tabs"),
        ("🔖", "Bookmark"),
        ("🏷️", "Label"),
        ("💰", "Money Bag"),
        ("💴", "Yen Banknote"),
        ("💵", "Dollar Banknote"),
        ("💶", "Euro Banknote"),
        ("💷", "Pound Banknote"),
        ("💸", "Money with Wings"),
        ("💳", "Credit Card"),
        ("🧾", "Receipt"),
        ("✉️", "Envelope"),
        ("📧", "E-Mail"),
        ("📨", "Incoming Envelope"),
        ("📩", "Envelope with Arrow"),
        ("📤", "Outbox Tray"),
        ("📥", "Inbox Tray"),
        ("📦", "Package"),
        ("📫", "Closed Mailbox with Raised Flag"),
        ("📪", "Closed Mailbox with Lowered Flag"),
        ("📬", "Open Mailbox with Raised Flag"),
        ("📭", "Open Mailbox with Lowered Flag"),
        ("📮", "Postbox"),
        ("🗳️", "Ballot Box with Ballot"),
        ("✏️", "Pencil"),
        ("✒️", "Black Nib"),
        ("🖋️", "Fountain Pen"),
        ("🖊️", "Pen"),
        ("🖌️", "Paintbrush"),
        ("🖍️", "Crayon"),
        ("📝", "Memo"),
        ("💼", "Briefcase"),
        ("📁", "File Folder"),
        ("📂", "Open File Folder"),
        ("🗂️", "Card Index Dividers"),
        ("📅", "Calendar"),
        ("📆", "Tear-Off Calendar"),
        ("🗒️", "Spiral Notepad"),
        ("🗓️", "Spiral Calendar"),
        ("📇", "Card Index"),
        ("📈", "Chart Increasing"),
        ("📉", "Chart Decreasing"),
        ("📊", "Bar Chart"),
        ("📋", "Clipboard"),
        ("📌", "Pushpin"),
        ("📍", "Round Pushpin"),
        ("📎", "Paperclip"),
        ("🖇️", "Linked Paperclips"),
        ("📏", "Straight Ruler"),
        ("📐", "Triangular Ruler"),
        ("✂️", "Black Scissors"),
        ("🗃️", "Card File Box"),
        ("🗄️", "File Cabinet"),
        ("🗑️", "Wastebasket"),
        ("🔒", "Locked"),
        ("🔓", "Unlocked"),
        ("🔏", "Locked with Pen"),
        ("🔐", "Locked with Key"),
        ("🔑", "Key"),
        ("🗝️", "Old Key"),
        ("🔨", "Hammer"),
        ("⛏️", "Pick"),
        ("⚒️", "Hammer and Pick"),
        ("🛠️", "Hammer and Wrench"),
        ("🗡️", "Dagger"),
        ("⚔️", "Crossed Swords"),
        ("🔫", "Pistol"),
        ("🏹", "Bow and Arrow"),
        ("🛡️", "Shield"),
        ("🔧", "Wrench"),
        ("🔩", "Nut and Bolt"),
        ("⚙️", "Gear"),
        ("🗜️", "Clamp"),
        ("⚖️", "Balance Scale"),
        ("🔗", "Link"),
        ("⛓️", "Chains"),
        ("🧰", "Toolbox"),
        ("🧲", "Magnet"),
        ("⚗️", "Alembic"),
        ("🧪", "Test Tube"),
        ("🧫", "Petri Dish"),
        ("🧬", "DNA"),
        ("🔬", "Microscope"),
        ("🔭", "Telescope"),
        ("📡", "Satellite Antenna"),
        ("💉", "Syringe"),
        ("🩸", "Drop of Blood"),
        ("💊", "Pill"),
        ("🩹", "Adhesive Bandage"),
        ("🩺", "Stethoscope"),
        ("🚪", "Door"),
        ("🛏️", "Bed"),
        ("🛋️", "Couch and Lamp"),
        ("🪑", "Chair"),
        ("🚽", "Toilet"),
        ("🚿", "Shower"),
        ("🛁", "Bathtub"),
        ("🪒", "Razor"),
        ("🧴", "Lotion Bottle"),
        ("🧷", "Safety Pin"),
        ("🧹", "Broom"),
        ("🧺", "Basket"),
        ("🧻", "Roll of Paper"),
        ("🧼", "Soap"),
        ("🧽", "Sponge"),
        ("🧯", "Fire Extinguisher"),
        ("🛒", "Shopping Cart"),
    ],
    "symbols": [
        ("🚬", "Cigarette"),
        ("⚰️", "Coffin"),
        ("⚱️", "Funeral Urn"),
        ("🗿", "Moai"),
        ("🏧", "ATM Sign"),
        ("🚮", "Litter in Bin Sign"),
        ("🚰", "Potable Water"),
        ("♿", "Wheelchair Symbol"),
        ("🚹", "Men's Room"),
        ("🚺", "Women's Room"),
        ("🚻", "Restroom"),
        ("🚼", "Baby Symbol"),
        ("🚾", "Water Closet"),
        ("⚠️", "Warning"),
        ("🚸", "Children Crossing"),
        ("⛔", "No Entry"),
        ("🚫", "Prohibited"),
        ("🚳", "No Bicycles"),
        ("🚭", "No Smoking"),
        ("🚯", "No Littering"),
        ("🚱", "Non-Potable Water"),
        ("🚷", "No Pedestrians"),
        ("📵", "No Mobile Phones"),
        ("🔞", "No One Under Eighteen"),
        ("☢️", "Radioactive"),
        ("☣️", "Biohazard"),
        ("⬆️", "Up Arrow"),
        ("↗️", "Up-Right Arrow"),
        ("➡️", "Right Arrow"),
        ("↘️", "Down-Right Arrow"),
        ("⬇️", "Down Arrow"),
        ("↙️", "Down-Left Arrow"),
        ("⬅️", "Left Arrow"),
        ("↖️", "Up-Left Arrow"),
        ("↕️", "Up-Down Arrow"),
        ("↔️", "Left-Right Arrow"),
        ("↩️", "Right Arrow Curving Left"),
        ("↪️", "Left Arrow Curving Right"),
        ("⤴️", "Right Arrow Curving Up"),
        ("⤵️", "Right Arrow Curving Down"),
        ("🔄", "Clockwise Vertical Arrows"),
        ("🔃", "Clockwise Down-Up Arrow"),
        ("📛", "Name Badge"),
        ("🔰", "Japanese Symbol for Beginner"),
        ("⭕", "Hollow Red Circle"),
        ("✅", "White Check Mark"),
        ("☑️", "Ballot Box with Check"),
        ("✔️", "Check Mark"),
        ("❌", "Cross Mark"),
        ("❎", "Cross Mark Button"),
        ("➰", "Curly Loop"),
        ("➿", "Double Curly Loop"),
        ("〽️", "Part Alternation Mark"),
        ("✳️", "Eight-Spoked Asterisk"),
        ("✴️", "Eight-Pointed Star"),
        ("❇️", "Sparkle"),
        ("‼️", "Double Exclamation Mark"),
        ("⁉️", "Exclamation Question Mark"),
        ("❓", "Red Question Mark"),
        ("❔", "White Question Mark"),
        ("❕", "White Exclamation Mark"),
        ("❗", "Red Exclamation Mark"),
        ("〰️", "Wavy Dash"),
        ("©️", "Copyright"),
        ("®️", "Registered"),
        ("™️", "Trade Mark"),
        ("#️⃣", "Keycap Number Sign"),
        ("*️⃣", "Keycap Asterisk"),
        ("0️⃣", "Keycap Digit Zero"),
        ("1️⃣", "Keycap Digit One"),
        ("2️⃣", "Keycap Digit Two"),
        ("3️⃣", "Keycap Digit Three"),
        ("4️⃣", "Keycap Digit Four"),
        ("5️⃣", "Keycap Digit Five"),
        ("6️⃣", "Keycap Digit Six"),
        ("7️⃣", "Keycap Digit Seven"),
        ("8️⃣", "Keycap Digit Eight"),
        ("9️⃣", "Keycap Digit Nine"),
        ("🔟", "Keycap: 10"),
        ("🔠", "Input Latin Uppercase"),
        ("🔡", "Input Latin Lowercase"),
        ("🔢", "Input Numbers"),
        ("🔣", "Input Symbols"),
        ("🔤", "Input Latin Letters"),
        ("🅰️", "A Button"),
        ("🆎", "AB Button"),
        ("🅱️", "B Button"),
        ("🆑", "CL Button"),
        ("🆒", "Cool Button"),
        ("🆓", "Free Button"),
        ("ℹ️", "Information Source"),
        ("🆔", "ID Button"),
        ("Ⓜ️", "Circled M"),
        ("🆕", "New Button"),
        ("🆖", "NG Button"),
        ("🅾️", "O Button"),
        ("🆗", "OK Button"),
        ("🅿️", "P Button"),
        ("🆘", "SOS Button"),
        ("🆙", "Up! Button"),
        ("🆚", "Vs Button"),
        ("🈁", "Japanese Here Button"),
        ("🈂️", "Japanese Service Charge Button"),
        ("🈷️", "Japanese Monthly Amount Button"),
        ("🈶", "Japanese Not Free of Charge Button"),
        ("🈯", "Japanese Reserved Button"),
        ("🉐", "Japanese Bargain Button"),
        ("🈹", "Japanese Discount Button"),
        ("🈚", "Japanese Free of Charge Button"),
        ("🈲", "Japanese Prohibited Button"),
        ("🉑", "Japanese Acceptable Button"),
        ("🈸", "Japanese Application Button"),
        ("🈴", "Japanese Passing Grade Button"),
        ("🈳", "Japanese Vacancy Button"),
        ("㊗️", "Japanese Congratulations Button"),
        ("㊙️", "Japanese Secret Button"),
        ("🈵", "Japanese No Vacancy Button"),
        ("🔴", "Red Circle"),
        ("🟠", "Orange Circle"),
        ("🟡", "Yellow Circle"),
        ("🟢", "Green Circle"),
        ("🔵", "Blue Circle"),
        ("🟣", "Purple Circle"),
        ("🟤", "Brown Circle"),
        ("⚫", "Black Circle"),
        ("⚪", "White Circle"),
        ("🟥", "Red Square"),
        ("🟧", "Orange Square"),
        ("🟨", "Yellow Square"),
        ("🟩", "Green Square"),
        ("🟦", "Blue Square"),
        ("🟪", "Purple Square"),
        ("🟫", "Brown Square"),
        ("◼️", "Black Medium Square"),
        ("◻️", "White Medium Square"),
        ("◾", "Black Medium-Small Square"),
        ("◽", "White Medium-Small Square"),
        ("▪️", "Black Small Square"),
        ("▫️", "White Small Square"),
        ("🔶", "Large Orange Diamond"),
        ("🔷", "Large Blue Diamond"),
        ("🔸", "Small Orange Diamond"),
        ("🔹", "Small Blue Diamond"),
        ("🔺", "Red Triangle Pointed Up"),
        ("🔻", "Red Triangle Pointed Down"),
        ("💠", "Diamond with a Dot"),
        ("🔘", "Radio Button"),
        ("🔳", "White Square Button"),
        ("🔲", "Black Square Button"),
    ],
}


# ─── Перевод названий категорий ─────────────────────────────────────────────


def get_category_translation(key: str) -> str:
    """Получить переведённое название категории.

    Args:
        key: Ключ категории (английский).

    Returns:
        Переведенное имя категории.
    """
    translations = {
        "smileys": tr("Smileys & People"),
        "gestures": tr("Gestures"),
        "hearts": tr("Hearts"),
        "nature": tr("Animals & Nature"),
        "food": tr("Food & Drink"),
        "travel": tr("Travel & Places"),
        "objects": tr("Objects"),
        "symbols": tr("Symbols"),
    }
    return translations.get(key, key)


def get_display_category(key: str) -> str:
    """Получить переведённое название категории.

    Args:
        key: Ключ категории (английский).

    Returns:
        Переведенное имя.
        "Translated название категории.
    """
    return get_category_translation(key)


class EmojiButton(QPushButton):
    """Кнопка для отображения одного emoji."""

    def __init__(self, emoji: str, parent: QWidget | None = None) -> None:
        """Инициализация кнопки emoji.

        Args:
            emoji: Символ emoji для отображения.
            parent: Родительский виджет.
        """
        super().__init__(emoji, parent)
        self.setFont(QFont("Segoe UI Emoji", 32))
        self.setFixedSize(50, 50)
        self.setCursor(Qt.CursorShape.PointingHandCursor)


class EmojiPickerDialog(QDialog):
    """Диалог выбора emoji с категориями, сеткой и поиском."""

    emoji_selected = pyqtSignal(str)

    def __init__(self, parent: QWidget | None = None) -> None:
        """Инициализация диалога выбора emoji.

        Args:
            parent: Родительское окно.
        """
        super().__init__(parent)
        self.setWindowTitle(tr("Emoji Picker"))
        self.setModal(True)
        self.resize(520, 620)

        self._current_category_key = ""
        self._all_emojis: list[tuple[str, str]] = []  # (emoji, name)
        self._emoji_font_size = 48

        self._build_ui()
        self._populate_categories()
        # Показываем первую категорию
        first_key = next(iter(EMOJI_DATA), "")
        self._show_category(first_key)

    def _build_ui(self) -> None:
        """Создать интерфейс диалога."""
        layout = QVBoxLayout(self)

        # Поиск
        search_label = QLabel(tr("Search emojis..."))
        search_label.setStyleSheet("font-weight: bold; margin-bottom: 4px;")
        layout.addWidget(search_label)

        self.search_input = QLineEdit()
        self.search_input.setPlaceholderText(tr("Search emojis..."))
        self.search_input.textChanged.connect(self._on_search_changed)
        layout.addWidget(self.search_input)

        # Категория
        cat_label = QLabel(tr("Category"))
        cat_label.setStyleSheet(
            "font-weight: bold; margin-top: 4px; margin-bottom: 4px;"
        )
        layout.addWidget(cat_label)

        self.category_combo = QComboBox()
        self.category_combo.setMinimumWidth(150)
        self.category_combo.activated.connect(self._on_category_changed)
        layout.addWidget(self.category_combo)

        # Сетка emoji
        grid_label = QLabel()
        grid_label.setStyleSheet(
            "font-weight: bold; margin-top: 4px; margin-bottom: 4px;"
        )
        grid_label.setText(tr("Emoji"))
        layout.addWidget(grid_label)

        self.list_widget = QListWidget()
        self.list_widget.setViewMode(QListWidget.ViewMode.IconMode)
        self.list_widget.setIconSize(QSize(80, 80))
        self.list_widget.setGridSize(QSize(90, 90))
        self.list_widget.setFlow(QListWidget.Flow.LeftToRight)
        self.list_widget.setWrapping(True)
        self.list_widget.setSpacing(4)
        self.list_widget.itemClicked.connect(self._on_emoji_clicked)
        # Скрываем текст под иконками — видны только emoji
        self.list_widget.setStyleSheet(
            "QListWidget::item { height: 86px; width: 86px; }"
        )
        layout.addWidget(self.list_widget)

    def _populate_categories(self) -> None:
        """Заполнить комбобокс категориями с переводом."""
        for key in EMOJI_DATA:
            display_name = get_display_category(key)
            # Сохраняем ключ в userData
            self.category_combo.addItem(display_name, userData=key)
        if self.category_combo.count() > 0:
            self._current_category_key = self.category_combo.itemData(0)

    def _show_category(self, category_key: str) -> None:
        """Показать emoji выбранной категории.

        Args:
            category_key: Ключ категории (английский).
        """
        self._current_category_key = category_key
        self.list_widget.clear()
        self._all_emojis = EMOJI_DATA.get(category_key, [])

        font = QFont("Segoe UI Emoji", self._emoji_font_size)
        for emoji, name in self._all_emojis:
            item = QListWidgetItem(emoji)
            item.setFont(font)
            item.setToolTip(name)
            self.list_widget.addItem(item)

    def _on_category_changed(self, index: int) -> None:
        """Обработчик смены категории.

        Args:
            index: Индекс выбранной категории.
        """
        category_key = self.category_combo.itemData(index)
        if category_key:
            self._show_category(category_key)
        self.search_input.clear()

    def _on_search_changed(self, text: str) -> None:
        """Обработчик поиска emoji.

        Args:
            text: Текст поиска.
        """
        if not text:
            # Если поиск пустой — показать текущую категорию
            self._show_category(self._current_category_key)
            return

        text_lower = text.lower()
        self.list_widget.clear()

        font = QFont("Segoe UI Emoji", self._emoji_font_size)
        for emoji, name in self._all_emojis:
            if text_lower in name.lower() or text_lower in emoji:
                item = QListWidgetItem(emoji)
                item.setFont(font)
                item.setToolTip(f"{name} ({text})")
                self.list_widget.addItem(item)

    def _on_emoji_clicked(self, item: QListWidgetItem) -> None:
        """Обработчик клика по emoji.

        Args:
            item: Элемент списка.
        """
        emoji = item.text()
        if emoji:
            self.emoji_selected.emit(emoji)
            self.accept()
